branch-defaults:
  master:
    environment: bootBW-dev2
    group_suffix: null
global:
  application_name: bootBW
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
